import Head from 'next/head';
import { Button } from '../components/buttons/Button';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Button href="/hotels">View all hotels</Button>
      </main>
    </div>
  );
}

// This function runs only on the server side
export async function getStaticProps() {
  // Instead of fetching your `/api` route you can call the same
  // function directly in `getStaticProps`
  const res = await fetch('https://jsonplaceholder.typicode.com/users');
  const data = await res.json();
  // Props returned will be passed to the page component
  return { props: { users: data } };
}
